### ISSUE TITLE
Contradiction between php-cs-test and php-insights-test using typehint comments

### ISSUE THREAD

**Issue by eisfeuer** [elbgoods/ci-test-tools#21]
Following Situation:
```php
HasMany::macro('sync', function (array $ids, array $options = []): array {
    /* @var HasMany $this */
    return OneToManySync::make($this, $ids, $options)->execute();
});
```

To pass php-cs-test I must start the typehint comment with `/*`
To pass php-insights-test I must start the typehint commment with `/**`

So I can't pass php-cs-test and php-insights-test

**Comment by Gummibeer** [comment]
phpinsights is right.
